Vagrant.configure("2") do |config|
    config.vm.define "vb" do |vb|
        config.vm.box = "centos/7"
        config.vm.network "public_network", ip: "192.168.1.121", bridge: "wlo1: Wi-Fi (AirPort)"
        vb.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
    end
end
